name: main

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        trdsql: [0.6.3, 0.7.4]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install trdsql and print version
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add trdsql $GITHUB_WORKSPACE
          asdf install trdsql ${{ matrix.trdsql }}
          asdf global trdsql ${{ matrix.trdsql }}
          trdsql -version
  test:
    strategy:
      matrix:
        trdsql: [0.6.3, 0.7.4]

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-test trdsql $GITHUB_WORKSPACE 'trdsql -version' --asdf-tool-version ${{matrix.trdsql}}
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*